server:
  port: 7001                  # 定义运行端口
eureka: 
  server:
    enable-self-preservation: false     # 设置为false表示关闭保护模式
    eviction-interval-timer-in-ms: 5000 # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance:                   # eureak实例定义
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称