server:
  port: 7103                  # 定义运行端口
security:
  basic:
    enabled: true         # 启用安全认证处理
  user:
    name: edmin           # 用户名
    password: mldnjava    # 密码
eureka: 
  client:             # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-a.com:7101/eureka,http://edmin:mldnjava@eureka-b.com:7102/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance:                   # eureak实例定义
    hostname: eureka-c.com # 定义Eureka实例所在的主机名称